### ISSUE TITLE
Add a i18n-sample-desktop-app

### ISSUE THREAD

**Issue by atilacamurca** [jhorstmann/i18n#10]
I'm trying to use this library in a desktop application, and I'm keep getting this exception:

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
    at java.util.ResourceBundle$CacheKey.calculateHashCode(ResourceBundle.java:593)
    at java.util.ResourceBundle$CacheKey.<init>(ResourceBundle.java:522)
    at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1259)
    at java.util.ResourceBundle.getBundle(ResourceBundle.java:1246)
    at net.jhorstmann.i18n.impl.DefaultResourceBundleProviderFactory$DefaultResourceBundleProvider.getResourceBundle(DefaultResourceBundleProviderFactory.java:21)
    at net.jhorstmann.i18n.I18N.getBundle(I18N.java:40)
    at net.jhorstmann.i18n.I18N.getBundle(I18N.java:45)
    at net.jhorstmann.i18n.I18N.tr(I18N.java:123)
    at org.sanusb.view.Main.addMenu(Main.java:105)
    at org.sanusb.view.Main.init(Main.java:88)
    at org.sanusb.view.Main.<init>(Main.java:83)
    at org.sanusb.view.Main$1.run(Main.java:63)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
    at java.awt.EventQueue.access$300(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:706)
    at java.awt.EventQueue$3.run(EventQueue.java:704)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

Can you put an example so I can find what I'm doing wrong? Thanks in advance.

**Comment by jhorstmann** [comment]
The behaviour between desktop application and unit test should be very similar, can you extract such a test from your code and post it somewhere for investigation?

You could also make sure that you have the files `META-INF/services/net.jhorstmann.i18n.LocaleProviderFactory` and `META-INF/services/net.jhorstmann.i18n.ResourceBundleProviderFactory`, you can look at the unit tests to see examples: https://github.com/jhorstmann/i18n/tree/master/i18n-core/src/test/resources/META-INF/services

I agree this could be documented better.

**Comment by atilacamurca** [comment]
I know it's too much to ask but here's the source code I'm working on

https://atilacamurca@bitbucket.org/atilacamurca/sanusb-java-gui.git

I'm working on the branch `i18n` https://bitbucket.org/atilacamurca/sanusb-java-gui/src/0e775d3bb8abc34a4812805fd2579eb4d9e83898/?at=i18n

Can you please take a look? I already added the files you mention and still got the same results. I call `i18n:gettext` task and `i18n:merge`.

**Comment by jhorstmann** [comment]
I had a look and I think the main issue is that the two files mentioned above are not copied to the target directory during the build, because you overwrite the `resources` directory in your `pom.xml`. You should keep the default `src/main/resources` directory and maybe add your `img` directory as another resource root.

Another issue might be that you have different configuration of the resource bundle name as `targetBundle` in the pom and during runtime in `src/main/resources/META-INF/services/net.jhorstmann.i18n.ResourceBundle`. I would suggest changing both to something like `org.sanusb.Messages`.

Let me know if this solves the issue.

**Comment by atilacamurca** [comment]
Great man, that's exactly it.

The alterations was:

```
<resources>
    <resource>
        <directory>resources/META-INF/services</directory>
    </resource>
    <resource>
        <directory>src/img</directory>
    </resource>
</resources>
```

and the ResourceBundle

```
<targetBundle>org.sanusb.Messages</targetBundle>
```

using the same in the `src/main/resources/META-INF/services/net.jhorstmann.i18n.ResourceBundle` file.

and some conflicts about the version of `slf4j-jdk14` and `slf4j-api`, that I have to upgrade from 1.5.11 to 1.7.5.

Thanks, I will leave the issue open so you can remember to put a desktop example.

**Comment by jhorstmann** [comment]
I'll close this since it started with a very specific error message, but I created issue #11 to improve the documentation, especially regarding required files.

**Comment by lengsovandara** [comment]
How do you generate po files?
